"""next one

Revision ID: 13a030c1904f
Revises: c3a81b57ffa1
Create Date: 2023-06-29 13:49:00.875915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a030c1904f'
down_revision = 'c3a81b57ffa1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickets_user_id', table_name='tickets')
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.create_index('ix_tickets_user_id', 'tickets', ['user_id'], unique=False)
    # ### end Alembic commands ###
