"""to-string

Revision ID: 46aa5ddd4c78
Revises: 13a030c1904f
Create Date: 2023-06-29 23:05:00.920201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46aa5ddd4c78'
down_revision = '13a030c1904f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
